### ISSUE TITLE
TypeScript  

### ISSUE THREAD

**Issue by carywreams** [google/styleguide#103]
If its in scope for this repo, would really like to see a TypeScript Style Guide.

So far, I've only found a recommendation to use the **Names** and **Styles** section from the official TypeScript contribution guidelines.

Thanks

**Comment by justinrknowles** [comment]
👍   especially now that Angular 2 is out and implemented in TypeScript.

**Comment by vapier** [comment]
https://google.github.io/styleguide/tsguide.html
