### ISSUE TITLE
Request: create styleguide for Go

### ISSUE THREAD

**Issue by FilipBrinkmann** [google/styleguide#107]
I use your styleguides with only minor changes for most of my code in any language. Since I recently started learning Go, I wanted to use your style from the start. I am quite surprised that this repository does not contain a styleguide for Go. It would be a great help for all Go programmers out there if you would shed some light on how you guys layout your Go code. Of course, Go's fmt does a lot of formatting by itself - it does not, however, answer questions on how to arrange methods, where and how to use documentation etc.

**Comment by tituswinters** [comment]
I'd start at golang.org and some of the docs, articles, and mailing lists there.  Go is handled very differently from other languages at Google (namely, Go is originally a Google project and operates very publicly, other languages are public languages and we sometimes discuss our usages - the two models are not the same).
