### ISSUE TITLE
cpplint does not detect build/header_guard error for .cuh files

### ISSUE THREAD

**Issue by jasjuang** [google/styleguide#113]
Suppose I have test.cuh

// Copyright 2016 jasjuang
# ifndef WRONG_PATH_CUH_
# define WRONG_PATH_CUH_

class test{
public:
//something
};
# endif // WRONG_PATH_CUH_

If I do python cpplint.py test.cuh

Done processing test.cuh
Total errors found: 0

but it should be showing the "#ifndef header guard has wrong style, please use: CORRECT_PATH_CUH_ [build/header_guard] [5]" error. 

If I rename test.cuh to test.h cpplint works normally.

**Comment by jasjuang** [comment]
To add onto this if test.cuh is 

// Copyright 2016 jasjuang

#ifndef CORRECT_BUT_LONGGGGGGGGGGGGGGGGGGGGGGGGGGGG_PATH_OVER_EIGHTY_CHARS_CUH_
#define CORRECT_BUT_LONGGGGGGGGGGGGGGGGGGGGGGGGGGGG_PATH_OVER_EIGHTY_CHARS_CUH_

class test{
public:
//something
};

#endif // CORRECT_BUT_LONGGGGGGGGGGGGGGGGGGGGGGGGGGGG_PATH_OVER_EIGHTY_CHARS_CUH_

this will show an " Lines should be <= 80 characters long  [whitespace/line_length] [2]" error, whereas if test.cuh is renamed to test.h no error will be shown. 

I think the problem is cpplint is not treating .cuh as a header file just like it's treating .h files.

**Comment by tituswinters** [comment]
I'm not familiar with .cu and .cuh as a common extension.  So I think first off, you'd have to convince me that those are common and ought to be supported.

**Comment by jasjuang** [comment]
These are CUDA extensions. A lot of people code in CUDA, and a lot of companies are looking for people who can code in CUDA, for example https://www.linkedin.com/jobs/cuda-jobs

**Comment by LukeCz** [comment]
Added configurable option for any extension type in pull request #183.

**Comment by jasjuang** [comment]
solved by #183
