### ISSUE TITLE
Google HTML/CSS Style Guide: HTTPS Security concerns

### ISSUE THREAD

**Issue by alanyee** [google/styleguide#114]
Currently, [Google's HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.xml) advocates in its "General Style Rules" under "Protocol" for an omission of "http:" and "https:". Correct me if I am wrong, but I have heard of security concerns where allowing the snippet to request over HTTP leads to attacks like [China's Man-on-the-Side Attack on GitHub](http://www.netresec.com/?page=Blog&month=2015-03&post=China%27s-Man-on-the-Side-Attack-on-GitHub). I propose that the style guide remove the practice of omitting the protocol, and instead advocate for the practice of using explicit calls to HTTPS.

**Comment by ejona86** [comment]
The recommendation uses HTTP when on HTTP and HTTPS when on HTTPS. If you are requesting the HTML page over HTTP, then you are already vulnerable. Specifying the HTTPS gains you little.
