### ISSUE TITLE
Python type hinting

### ISSUE THREAD

**Issue by jmakov** [google/styleguide#117]
Hi,

In the python style guide the part on comments only mention that the types should be described. However it doesn't mention the capability to declare types in docstrings e.g. 
`"""Args:
  my_house (lib.base.House): my new house
"""`
Would adding type hinting break google style guide?

**Comment by gpshead** [comment]
Authors are free to describe types however they want after the `arg_name:` that the code reviewer agrees with as being consistent within the file or library. Putting it before the : is not desirable as that would break pylint warnings about the contents of the Args: section.  (Probably only in our internal pylint? I'm not sure at the moment if we have released that Google style docstring pylint checker)  For example:

```
  Args:
      my_house: (lib.base.House) my new house.
```

We'll be adopting official Python [PEP484 type annotation](https://www.python.org/dev/peps/pep-0484/) syntax in the future.  It is not docstring based.

Docstrings are meant for human consumption, please keep them readable for us humans. :)

**Comment by jmakov** [comment]
Ok, that helps and even answers the question. Thanks for the quick response!

**Comment by gpshead** [comment]
FYI, if you want a pylint plugin for Google Python style docstrings, the Chromium project has one:
 https://chromium.googlesource.com/chromiumos/chromite/+/master/cli/cros/lint.py
