### ISSUE TITLE
cppguide: What is Google's stance on pimpl idiom?

### ISSUE THREAD

**Issue by jasjuang** [google/styleguide#119]
Pimpl is not mentioned in the cppguide so I am wondering what is Google's stance on pimpl idiom.

A brief overview of Pimpl is 

Put all the private member variables into a struct.
Put the struct definition in the .cpp file.
In the header file, put only the ForwardDeclaration of the struct.
In the class definition, declare a smart pointer to the struct as the only private member variable.
The constructors for the class need to create the struct.
The destructor of the class needs to destroy the struct (possibly implicitly due to use of a smart pointer).
The assignment operator and CopyConstructor need to copy the struct appropriately or else be disabled.

Benefits:
Changing private member variables of a class does not require recompiling classes that depend on it, thus make times are faster, and the FragileBinaryInterfaceProblem is reduced.
The header file does not need to #include classes that are used 'by value' in private member variables, thus compile times are faster.
Hide implementation details.

Drawbacks:
More work for the implementor.
Doesn't work for 'protected' members where access by subclasses is required.
Somewhat harder to read code, since some information is no longer in the header file.
Run-time performance is slightly compromised due to the pointer indirection, especially if function calls are virtual (branch prediction for indirect branches is generally poor).

More in http://c2.com/cgi/wiki?PimplIdiom

Does Google recommend using this design pattern? Does Google use this type of design pattern internally?

**Comment by geoffromer** [comment]
The general principle is that anything not specifically forbidden is allowed (within reason), so the pimpl idiom is allowed. However, it's not particularly encouraged, and in my experience it seems to be quite rare in Google code.
