### ISSUE TITLE
Update JavaScript Reference for ES2015 (ES6)

### ISSUE THREAD

**Issue by felguerez** [google/styleguide#123]
Hey,

It looks like the JavaScript style guide does not take into account updates to the language with ES2015 (ES6). For example, the guide suggests always using `var` for variable declarations, which may have been best practice for the sake of lexical scoping, but does not take into account the new keywords `let`, `const`, and the concept of immutability – [const seems to be preferred by many these days](http://programmers.stackexchange.com/questions/278652/how-much-should-i-be-using-let-vs-const-in-es6).

Is this styleguide actively maintained? If so, it'd be great to see it account for the updates to the language that occurred over the last year or so.

**Comment by shicks** [comment]
We have an ongoing effort to update (basically, completely rewrite) the guide and then (re)externalize it.  It's a bit stalled at the moment, but if it doesn't happen by the end of this quarter, I'm going to be very, very sad (and will push to escalate).

**Comment by proehlen** [comment]
Any update on this?  Would love to switch to a style guide used / backed by Google but I need to use the new language features.

**Comment by kevinrambaud** [comment]
bump

**Comment by shicks** [comment]
I'm planning to take a look at this when I return from leave in a few weeks.

**Comment by Evoke-PHP** [comment]
bump

**Comment by shicks** [comment]
I believe this is resolved and should be closed.  Do you see it otherwise?
