### ISSUE TITLE
Can't see the Javascript guide (worked like a charm yesterday...)

### ISSUE THREAD

**Issue by Cobraeti** [google/styleguide#127]
Hi,
I was using your Javascript guide as a reference to document my Node.js modules for JSDoc (
an exellent work elsewhere :wink:).
But today, I can no more access it and I'm not really good at reading docs as sources...
Chrome gives me a white page and just these logs (seems to be just warnings):

```
Resource` interpreted as Document but transferred with MIME type application/xml: "https://google.github.io/styleguide/javascriptguide.xml".
Navigated to https://google.github.io/styleguide/javascriptguide.xml
javascriptguide.xml:2 Resource interpreted as Stylesheet but transferred with MIME type application/xml: "https://google.github.io/styleguide/styleguide.xsl".
```

And Firefox and IE refuse to load the page, even offline...
Is there a way to get a previous version offline without istalling Git on my computer? (not that I don't like the tool, but it is my professional computer and has already too much of these tools for internal purposes :weary:)

**Comment by wieczorek1990** [comment]
Iceweasel shows `Error loading stylesheet: Parsing an XSLT stylesheet failed.`

**Comment by wieczorek1990** [comment]
The last commit broke it. You can view the guides locally:

```
git clone https://github.com/google/styleguide.git
cd styleguide
git checkout 8c09ccf
# open in browser
```

**Comment by wieczorek1990** [comment]
https://github.com/google/styleguide/pull/128

**Comment by Cobraeti** [comment]
Hi,
Sorry I haven't see it was already working online, so I think I could close this issue ;)
Thanks again for this good reference ;)
