### ISSUE TITLE
Update the Python Style guide pyguide.html from Google's internal version.

### ISSUE THREAD

**Issue by gpshead** [google/styleguide#140]
It hasn't been updated since 424ad34281beb67dcb5cd9294d638d564169d061 in 2012. We need to get this internal -> external sync update process automated.

**Comment by jayeye** [comment]
(xoogler here) I recall that the internal style guide for Python mandated two-space indents, just like for C++ and Java. Has this changed, or is this a deliberate departure from the internal style to accommodate the more common 4-space indent per PEP8?

**Comment by gpshead** [comment]
Yes, internally we use 2 spaces to match our C++ code.  We try not to pollute the rest of the world with that practice so that we're closer to PEP8. :)   Some open source Google projects do choose to use 2 but we generally recommend that people reindent to 4 when releasing as it makes contributions from others less frustrating.

**Comment by gpshead** [comment]
https://github.com/google/styleguide/blob/gh-pages/pyguide.md exists and is setup to actually be regularly updated from our internal version!

we need to redirect pyguide.html to it.

**Comment by gpshead** [comment]
I just merged https://github.com/google/styleguide/pull/394 after some pre-requisite cleanup which now causes the pyguide.html url to show the rendered markdown version.  Now there is no more ancient version marked "deprecated" with a url pointing to the new one. :)
