### ISSUE TITLE
shell styleguide conflicts with indented <<- here documents

### ISSUE THREAD

**Issue by sukima** [google/styleguide#146]
In Bash an indented heredoc will only work if you use tabs. Since the guides explain that only spaces (for which I prefer) are to be used it conflicts with how Bash interprets here documents.
#### Bash man page

> If the redirection operator is `<<-`, then all leading tab characters are stripped from input lines and the line containing delimiter. This allows here-documents within shell scripts to be indented in a natural fashion.
> ~ http://linux.die.net/man/1/bash
#### Unix & Linux StackExchange Answer

> Note that **you must use tabs**, not spaces to indent the here-doc.
> (emphasis theirs) ~ http://unix.stackexchange.com/a/76483/8541

Maybe adding a section for here documents and when not to use indentation style regarding them would help.

**Comment by vapier** [comment]
Commit 729557a4a28c1a74f01c23599e4f06ac533718fc now allows tabs for heredocs.

> https://google.github.io/styleguide/shellguide.html#indentation
> Exception: The only exception for using tabs is for the body of <<- tab-indented [here-document](https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Here-Documents).
