### ISSUE TITLE
Link in Objective-C Guide returns 404

### ISSUE THREAD

**Issue by tomlutzenberger** [google/styleguide#150]
Link to [Google's Open Source C++ Style Guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.xml) in the section "[Background](https://google.github.io/styleguide/objcguide.xml#Background)" returns a 404 error.

**Comment by vapier** [comment]
this was fixed in commit c5197bfc480154e85ac3be09cb4d0833427e09a7
