### ISSUE TITLE
Incorrect import for Intellij 2016.2 

### ISSUE THREAD

**Issue by Sahasrara** [google/styleguide#173]
We need an updated xml for the latest version of Intellij.  The current one is not formatted correctly.
To reproduce, just download intellij 2016.2, import the google code style xml for intellij, and examine the indentation rules (for java as an example).  For me they show up as 4 spaces instead of the desired 2.

**Comment by nameetpai** [comment]
+1

**Comment by judomu** [comment]
Workaround: Use the "Eclipse Code Formatter"-Plugin with the Eclipse Code Style :/

**Comment by faketrader** [comment]
I found this pull request #75: Add Java code style for IntelliJ 15
It works on 2016.3.

**Comment by shicks** [comment]
I just merged #209 - hopefully that addresses this issue sufficiently.  Feel free to reopen if not.

**Comment by geekecom** [comment]
http://stackoverflow.com/questions/42979700/how-to-configure-google-java-code-formatter-in-intellij-idea-17/42979701#42979701
