### ISSUE TITLE
Java style confirmation on space after synchronized

### ISSUE THREAD

**Issue by rnveach** [google/styleguide#206]
Hi, I was hoping to find confirmation on the styling for Java's `synchronized` keyword, specifically `4.6.2` if a whitespace should appear after it for a synchronized block.

The guide states: https://github.com/google/styleguide/blob/db0a26320f3e930c6ea7225ed53539b4fb31310c/javaguide.html#L486-L494
> a single ASCII space also appears in the following places
Separating any reserved word ... from an open parenthesis (() that follows it on that line

They do not give synchronized block as an example, but to me it is a keyword with an open parenthesis following it.
So should it be written as `synchronized (variable) {}` (with space) or `synchronized(variable) {}` (without space).
The eclipse formatter gives it a space, but it looks to be almost 2 years old. https://github.com/google/styleguide/blob/4293832aaa9f48b906bf25245bdc4f11c82df1c2/eclipse-java-google-style.xml#L282

**Comment by ejona86** [comment]
Yes, synchronized should have a space after it.

**Comment by rnveach** [comment]
Thanks for the clarification.
