### ISSUE TITLE
Java Style Guide: One-character local variables

### ISSUE THREAD

**Issue by romani** [google/styleguide#214]
https://google.github.io/styleguide/javaguide.html#s5.2.7-local-variable-names

does not say anything about one-character names.

Here there is comment that one-character names should be ok - https://github.com/google/guava/issues/1891#issuecomment-63231281

Please confirm that one-character names are ok.

**Comment by dimo414** [comment]
I can confirm that one-character local variable names are permitted. As part of https://github.com/google/styleguide/pull/151 I loosened the guidance around single-character variable names. Note they are still discouraged (but permitted) in public method parameters.

While not detailed in the style guide (since it's subjective) we encourage people to limit their use of single-letter variable names to industry-wide standard usages (e.g. `i`, `j`, `k` for counters, `e` for exceptions, etc.).

**Comment by romani** [comment]
@dimo414 , thanks for reply.

>e for exceptions, etc

According to http://checkstyle.sourceforge.net/reports/google-style/guava/ , exception parameters are not allowed to be single characters. We could update regexp to be `^e|t|([a-z][a-zA-Z0-9]*)$` it will allow well known short names as `e` and `t` only. 
Or you want to remove that constraint completely and allow any one character name ?

> Note they are still discouraged (but permitted) in public method parameters.

we caught this update and addressed it. But we report violation on one-character arguments of public methods.
As representative of google style do you want completely allow one-character names ?
"discourage" never works well with humans, it is either violation or not.
We want that checksyle config follows guide as much as possible. 
For examples of guava - http://checkstyle.sourceforge.net/reports/google-style/guava/ , search for "LocalVariableName"

> (e.g. i, j, k for counters

we already have option to skip loops counters - [example](https://github.com/checkstyle/checkstyle/blob/c25004bd0304d3c7466783c637e9c49bd5ebc72f/src/main/resources/google_checks.xml#L132)

**Comment by dimo414** [comment]
Personally, I would encourage dropping the one-character requirement entirely as it's simply too subjective whether a given example is acceptable or not, and there are many common cases where it's perfectly reasonable.

I can't speak authoritatively about Google Style, but per @kevinb9n's comment in https://github.com/google/guava/issues/1891 ("*I think that checkstyle should stop warning on single-character names.*") I believe we're on the same page. Kevin certainly signed off on the style guide change I submitted that loosened the one-character language.

I appreciate your point that "*"discourage" never works well with humans, it is either violation or not.*", but I think it's too heavy-handed to ban them outright. I suggest having checkstyle simply allow them.

**Comment by romani** [comment]
Checkstyle config will be updated - checkstyle/checkstyle#3702
