### ISSUE TITLE
Java Style Guide: single line javadoc with at-clauses

### ISSUE THREAD

**Issue by romani** [google/styleguide#215]
https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line

>  The single-line form may be substituted when there are no at-clauses present, and the entirety of the Javadoc block (including comment markers) can fit on a single line.

Here is ideas that guide is not correct:
https://github.com/google/guava/issues/1891#issuecomment-64281498

please confirm what is correct rules to allow single line javadocs.

**Comment by dimo414** [comment]
@kevinb9n any objection to just removing "there are no at-clauses present, and " from §7.1.1?

**Comment by romani** [comment]
@kevinb9n , please reply , there are more and more requests on this issue.
One more: checkstyle/checkstyle#3762

**Comment by cpovirk** [comment]
How about we just call them "block tags," as the Javadoc documentation does?

**Comment by romani** [comment]
if you define what is "block tags" in guide it is completely fine.

**Comment by kevinb9n** [comment]
Looks like we amended this a while back

https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line
