### ISSUE TITLE
Swift Style Guide

### ISSUE THREAD

**Issue by grantkemp** [google/styleguide#222]
I can guess that with the amount of work you are doing on Swift -there should be a Guide. I want to to contribute to one of the open source libraries to integrate Google Api so would be fab to have something to use, even in beta format.

**Comment by minikin** [comment]
Good idea!

**Comment by nuomi1** [comment]
https://google.github.io/swift/

**Comment by marciniwanicki** [comment]
Thanks for https://google.github.io/swift/ (source: https://github.com/google/swift/tree/gh-pages), it's really nice style guide. Are you planning to add it to https://github.com/google/styleguide ?

**Comment by vmsp** [comment]
The guide mentions that "It is a living document and the basis upon which the formatter is implemented.". Is this formatter available?

**Comment by vapier** [comment]
Swift guide is released & linked from the main index
