### ISSUE TITLE
Migrate to Gitbooks?

### ISSUE THREAD

**Issue by grantkemp** [google/styleguide#223]
The documentation isn't really clear and plesant to read. Would be excellent to move this to : 

https://www.gitbook.com/ ( free as this is an Os project)

**Comment by EllieLockhart** [comment]
Has any discussion about this issue taken place since this initial posting? Or is this a resolved/addressed concern?

**Comment by shicks** [comment]
The style guides are generally maintained internally and synced out to GitHub periodically.  Migrating to Gitbooks would break that process, so it's very unlikely that it would happen.

**Comment by vapier** [comment]
yeah, not a bad idea, but would require a lot of investment across many teams that Google isn't going to invest in
