### ISSUE TITLE
is there  idea-html/css-google-style.xml?

### ISSUE THREAD

**Issue by ChlZhYa** [google/styleguide#251]

**Comment by tonyruscoe** [comment]
We have this Google HTML/CSS Style Guide:

https://google.github.io/styleguide/htmlcssguide.html

Is that what you were looking for?

**Comment by ChlZhYa** [comment]
Thanks.I want a html/css style XML file like intellij-java-google-style.xml so that i can import it to Webstorm. My English is very poor,i'm not sure whether you can understand what i say......

**Comment by tonyruscoe** [comment]
Thanks, I understand now. Sorry, we don’t have that.

**Comment by ChlZhYa** [comment]
thanks

**Comment by HeiShuXianSheng** [comment]
@ChlZhYa 你找到了吗？did you find it?
