### ISSUE TITLE
Java style guide: state whether to indent blank lines or not

### ISSUE THREAD

**Issue by Stummi** [google/styleguide#262]
Currently the style Guide does not say anything regarding if indentation should be applied to blank lines or not, to match the upper scope. The code examples seem to not intent blank lines, which also is what I prefer, but I think the style guide should state this explicitly

**Comment by gpshead** [comment]
A blank line is blank. There should be no trailing whitespace.  Noone should be try to "indent" blank lines. But I don't think we should mention "indenting blank lines" in any style guide. That concept doesn't make sense.

The C++ style guide states "Never put trailing whitespace at the end of a line." which seems like reasonable statement for all language style guides to adopt.

**Comment by cdeszaq** [comment]
> The C++ style guide states "Never put trailing whitespace at the end of a line." which seems like reasonable statement for all language style guides to adopt.

Including that language solves this issue in a very unambiguous way.
