### ISSUE TITLE
Error message 'null' on trying to import in version 2017.2.6

### ISSUE THREAD

**Issue by neonidian** [google/styleguide#299]
On trying to import the google code style in my latest version of IntelliJ 2017.2.6, I am getting a 'null' error. Could not find any other logs or can I ?

**Comment by caipanjin** [comment]
same problem, please fix it.

**Comment by viktorianer** [comment]
same problem in 2017.3

**Comment by viktorianer** [comment]
You should check the file format after download. It should be xml and not html.
