### ISSUE TITLE
C++ Style: Ambiguity in naming of static const(expr) class members

### ISSUE THREAD

**Issue by macmason** [google/styleguide#307]
In the C++ style guide, under "Class Data Members" we have:

> Data members of classes, both static and non-static, are named like ordinary nonmember variables, but with a trailing underscore.

and then under "Constant Names" we have: 

> Variables declared constexpr or const, and whose value is fixed for the duration of the program, are named with a leading "k" followed by mixed case.

What's the recommendation for a static const(expr) member variable? All of `variable_`, `kVariable`, and `kVariable_` can be justified if you squint hard enough.

**Comment by tituswinters** [comment]
Naming is about meaning - static const is most likely actually constant for the life of the program. Telling the reader that with the kFoo naming sounds right.

**Comment by macmason** [comment]
That's what we concluded as well. I don't have a suggestion for improving the wording, other than maybe adding "including member variables" under "Constant Names". I could PR that if that's useful.

**Comment by tituswinters** [comment]
I could go either way on PRs right now - I'm trying to get the C++ guide moved and hosted with Abseil so that there are C++ people that are actually tasked with monitoring it.  Stuff sitting here gets neglected and out of date.

**Comment by macmason** [comment]
Makes sense. If this moves to abseil, and I remember, I'll re-open over there.
