### ISSUE TITLE
Publish an official TypeScript style guide

### ISSUE THREAD

**Issue by kblicharski** [google/styleguide#310]
Considering the popularity of Angular, I think it would be appropriate for Google to publish the rules used in the [ts-style](https://github.com/google/ts-style) project's [tslint.json](https://github.com/google/ts-style/blob/master/tslint.json) file in a format similar to [the official JavaScript style guide](https://google.github.io/styleguide/jsguide.html) for TypeScript-specific features.

It would be far simpler than trying to parse the tslint.json file in order to figure out why certain rules are the way they are.

I know this is a duplicate of #103, I figured this is worth resurfacing now since that issue is so old.

**Comment by freshp86** [comment]
Such a style guide already exists at https://google.github.io/styleguide/tsguide.html, so I think this can be closed.
