### ISSUE TITLE
Kotlin style guide

### ISSUE THREAD

**Issue by bao7uo** [google/styleguide#314]
Would be great to see a Kotlin style guide :-)

**Comment by jpwroberts** [comment]
It's at [https://android.github.io/kotlin-guides/style.html](https://android.github.io/kotlin-guides/style.html)

A link from https://github.com/google/styleguide would be nice :-)

**Comment by immadolf** [comment]
How can i download the Kotlin style guide and import into IDEA?

**Comment by nhalase** [comment]
There isn't a need for a Kotlin import for IDEA. Go into Settings -> Editor -> Code Style -> Kotlin and in the top right corner, you can select "Set from..." and select Java from the Language drop-down. It will import the Java style for Kotlin.

**Comment by bao7uo** [comment]
#365 adds a link to the external Kotlin Style Guide

**Comment by cc189** [comment]
> It's at https://android.github.io/kotlin-guides/style.html
> 
> A link from https://github.com/google/styleguide would be nice :-)

No update as March 2021 😞  --- That's how I came to this issue.
