### ISSUE TITLE
JSON: I can't "toggle summary" as it leads to JS errors

### ISSUE THREAD

**Issue by quinefang** [google/styleguide#316]
On the "Google JSON Style Guide" and "Shell Style Guide" pages, I clicked the "Toggle all summaries" button, but nothing happened. I opened the DevTools console and found some error output as follows: 
![screenshot from 2018-01-10 10-15-51](https://user-images.githubusercontent.com/20615146/34752768-4692c1f0-f5ef-11e7-8beb-fcdb92ec7ed9.png)

**Comment by quinefang** [comment]
Currently the only thing I can do is to manually execute the following code in the DevTools console instead:
```
const els = document.getElementsByClassName('stylepoint_body');
for (let i=0; i<els.length; i++) {  
  els[i].style.display = 'block'; 
}
```

**Comment by vapier** [comment]
the shell guide has been recently updated and no longer has "toggle all" in it at all.  so we can drop that from this discussion.

the JSON guide is working for me ...
https://google.github.io/styleguide/jsoncstyleguide.xml
