### ISSUE TITLE
A beginner question

### ISSUE THREAD

**Issue by quinefang** [google/styleguide#317]
I am really a VIM beginner, how to use [google_python_style.vim](https://github.com/google/styleguide/blob/gh-pages/google_python_style.vim)?

**Comment by quinefang** [comment]
Finally I got the answer from the internet:

1. move google_python_style.vim to ~/.vim/indent/python.vim
1. edit ~/.vimrc, append "filetype indent on" and "set autoindent"

That should works.

**Comment by Sangdol** [comment]
In my case, I had to copy the script to `~/.vim/after/indent/python.vim` as the built-in python indent script overridden the one I added to `~/.vim/indent/python.vim`. 

I was able to see the loaded order by `:scriptnames` command.
