### ISSUE TITLE
Fix a broken link in cppguide.html

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/styleguide#32]
```
There is a broken link linking to `Macro_Names` instead of `#Macro_Names`. 
Refer to the attachment for the exact patch.

```

Original issue reported on code.google.com by `cyen0...@gmail.com` on 22 Oct 2014 at 10:46

Attachments:
- [cppguide.html.patch](https://storage.googleapis.com/google-code-attachments/google-styleguide/issue-32/comment-0/cppguide.html.patch)

**Comment by vapier** [comment]
i think this is fixed now
