### ISSUE TITLE
PMD ruleset for Google Cloud

### ISSUE THREAD

**Issue by javatlacati** [google/styleguide#321]
I know it's not strictly style but I suggest including a PMD ruleset for gcloud based projects.

i.e. https://raw.githubusercontent.com/GoogleCloudPlatform/google-cloud-java/master/pmd.xml

**Comment by derekm** [comment]
Those old rule definitions also need to be updated for the latest releases of PMD. Using gcloud PMD rulesets causes tons of rule name change warnings in latest releases of PMD, and things will get worse as PMD 7.0 is released and deprecated rules are removed.
