### ISSUE TITLE
Import of eclipse-java-google-style.xml  fails for Oxygen.3

### ISSUE THREAD

**Issue by timmolter** [google/styleguide#338]
Version: Oxygen.3
 Release (4.7.3)
Build id: 20180308-1800

<img width="534" alt="screen shot 2018-03-29 at 13 05 15" src="https://user-images.githubusercontent.com/738972/38085904-aa2ed19a-3352-11e8-8aad-800290ed3979.png">

**Comment by Lonzak** [comment]
I had that too. Did you take a look into the file? I did the mistake of doing a right-click here https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml and directly downloading it. But then you download an HTML file and not the actual XML file. Better use this [link](https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml).

**Comment by timmolter** [comment]
That was it. Thanks!
