### ISSUE TITLE
README.md should link to pyguide.md & render that as markdown

### ISSUE THREAD

**Issue by gpshead** [google/styleguide#357]
https://google.github.io/styleguide/ appears to display README.md rendered properly.

But it links to https://google.github.io/styleguide/pyguide.html which is the obsolete python style guide.

If I try to open https://google.github.io/styleguide/pyguide without a file extension it opens the html file.  :(
If I try to open https://google.github.io/styleguide/pyguide.md it displays the raw markdown instead of rendering it. :(

How does github.io even work?

**Comment by sfdye** [comment]
@gpshead Please see my attempt in #394 .
