### ISSUE TITLE
Doesn't work correctly with Chromium

### ISSUE THREAD

**Issue by celem** [google/styleguide#370]
I filed a bug report with Chromium.org [https://bugs.chromium.org/p/chromium/issues/detail?id=847415#c32](url) and they resolved that problem is with shell.xml is imported as part of the stylesheet imported by the offending Google web page. [https://google.github.io/styleguide/shell.xml?mc_cid=2498c2fa19&mc_eid=5ec9af561f](url)

For the record I am using Chromium Version 67.0.3396.79 (Official Build) Arch Linux (64-bit) but the older version also failed..

**Comment by foutrelis** [comment]
Fixed in the Arch Linux Chromium package (67.0.3396.87-2).

**Comment by techtonik** [comment]
See the problem with Version 67.0.3396.79 (Developer Build) Fedora Project (64-bit)

**Comment by celem** [comment]
Fixed in Version 67.0.3396.87 (Official Build) Manjaro Linux (64-bit)

**Comment by techtonik** [comment]
For some reason links in the first post are not rendering:
* https://bugs.chromium.org/p/chromium/issues/detail?id=847415#c32
* https://google.github.io/styleguide/shell.xml?mc_cid=2498c2fa19&mc_eid=5ec9af561f

**Comment by vapier** [comment]
the shell style guide is migrated to md/html now, so any xml issues are moot
