### ISSUE TITLE
[pyguide] Should there be a separator for end of lists

### ISSUE THREAD

**Issue by gabipetrovay** [google/styleguide#377]
In the cases there the syntax allows it, should there be an extra (redundant) separator at the end of lists:

```python
foo(
    arg1=1,
    arg2=2,
)
```

Is the comma after the 2nd argument good or bad style?

I don't see/find this in the main style guide.

**Comment by gabipetrovay** [comment]
There is an example in section 3.6 [Whitespaces](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#36-whitespace) with a dictionary which might give a clue that the style guide might recommend it. Maybe a sub-section for this case?

```python
dictionary = {
    'foo': 1,
    'long_name': 2,
}
```

**Comment by gpshead** [comment]
I don't think we've put this in the guide yet, but the presence of a trailing comma after the last item is used as an indicator for Python autoformatters such as [YAPF](https://github.com/google/yapf), which we use internally, to decide which way it should format the list.

For multi-line sequences of items, a trailing comma makes life easier when adding new items or rearranging items in a list with an editor as there is no need to remember to go find the missing comma and add it.

**Comment by gpshead** [comment]
I pushed an update that addresses this:
 https://google.github.io/styleguide/pyguide.html#341-trailing-commas-in-sequences-of-items
