### ISSUE TITLE
pyguide HTML was stale for 5 years then suddenly deprecated

### ISSUE THREAD

**Issue by mcallaghan-sandvine** [google/styleguide#381]
So surprise!
https://github.com/google/styleguide/commit/1707ccb7d18e4980870ce0ea6ab3d380f9a36a30

https://google.github.io/styleguide/pyguide.html
>  Revision 2.59 This is an obsolete unmaintained copy of the style guide. Please use pyguide.md instead. 

I know of _tons_ of people/companies that were leveraging this as the law of Python. (or at least a 3rd party reference/supplicant to the PEP)

As per
https://github.com/google/styleguide/commit/1707ccb7d18e4980870ce0ea6ab3d380f9a36a30#commitcomment-29815046

Is it possible to:
 1. completely delete the content (retain the stub landing page for manual user redirect)
   * -- no point in keeping it around if it's been dead for 5 years
 2. someone from Google please do an assessment of "what's changed" over the past 5 years
   * -- compare HTML to MD -- and provide a "1-year-shelf-life" matrix that tries to succinctly describe the major differences so that people can easily consume the new style guide

Would be awesome! Thank you.

**Comment by mcallaghan-sandvine** [comment]
Could anyone @google-admin triage this and determine if Google will address the concerns?

**Comment by sfdye** [comment]
+1. Can't we just render the html from markdown? It's confusing to still keep the old html version with a tiny deprecation notice.

**Comment by mcallaghan-sandvine** [comment]
(not sure if I agree that the spirit of this ticket was addressed by #394)

**Comment by gpshead** [comment]
Well, the old html file is gone and is now rendered from the current markdown which addresses (1).

For (2) if someone wants a "what's changed" matrix over the years, they'll have to create it themselves, sorry. :/

**Comment by mcallaghan-sandvine** [comment]
Agreed (1) is addressed.

(2) is what was concerning to me.  Many developers have been referencing a "stale guide" without knowledge that it was stale.  Now suddenly its gone and a new guide is published, but adaptation is needed and some sort of summary of changes is needed IMO.  Imagine users writing code to that stale style, and now desiring to refresh/update on the newer guide, it would be nice to know how similar or not the new guide is. (i.e. how bad is code that has been written to the previous guide, compared to the new style guide?)

**Comment by gpshead** [comment]
The fundamental themes have not changed.  Code written to the old version of the style guide is not likely to be considered bad by anyone.

**Comment by mcallaghan-sandvine** [comment]
:+1: thank you
