### ISSUE TITLE
C++ style guide no longer has a table of contents

### ISSUE THREAD

**Issue by rongoldman-tri** [google/styleguide#387]
The latest change to the C++ style guide has removed the table of contents at the top of the page. Please put it back! It's really hard to find the right section without it. Thanks.

-- Ron --

**Comment by nmayorov** [comment]
Huge +1.

**Comment by joel-porquet** [comment]
Please fix.

**Comment by manshreck** [comment]
We've added the TOC back. We're converting some files to markdown and this <div> was unintentionally deleted.

**Comment by tituswinters** [comment]
Fixed in https://github.com/google/styleguide/pull/389
