### ISSUE TITLE
cpplint: override is NOT redundant when declaring final

### ISSUE THREAD

**Issue by reinerh** [google/styleguide#388]
When declaring a class method as "final override", cpplint complains that `"override" is redundant since function is already declared as "final"`.
But this is not true, they both have different meanings.
override tells the compiler that you want to override a function of a base class, while final means that you don't want other subclasses to override it.
If I would remove the "override" declaration, it would no longer be noticed if the overridden function of the base class changes its signature.

And when using the (g++) compiler flag "-Wsuggest-override", the compiler actually suggests to mark it as override, even if it is already marked as final.

**Comment by tituswinters** [comment]
Semantically, "final" implies "override."  See sandbox example:
https://godbolt.org/g/Dop4qA
(comment out Child::Fails() and the build succeeds.)

If you change the signature in the parent class, the mismatch is caught with only "final - override is unnecessary.

As far as gcc warning flags go: gcc has a (long) history of introducing flags that sound nice but are missing some subtleties in design.  This sounds like it goes on that list.
