### ISSUE TITLE
Request: A Google-sanctioned style guide for Ruby

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/styleguide#40]
I know that Google prefers Python over Ruby. But for organizations that like using Ruby, and like using Google Style, being able to refer to a Google document on Ruby style would be more useful than having to point to multiple style guides.

What do you think?

Original issue reported on code.google.com by `apenneba...@gmail.com` on 13 Feb 2015 at 8:38

**Comment by vapier** [comment]
Google maintains styleguides for languages that it uses.  we don't use Ruby anywhere, so we don't have a styleguide for it, and I don't see how we'd have anything useful to contribute to one.  you'd be better off going with experts in the Ruby community.
