### ISSUE TITLE
Java: 4.1.2 example: Missing opening brace in else if

### ISSUE THREAD

**Issue by taurus227** [google/styleguide#412]
The Java Style Guide states:

> **[4.1.1 Braces are used where optional](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used)**
> Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.
> 

But the example in the immediately following section contains:

> **[4.1.2 Nonempty blocks: K & R style](https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style)**
> `    } else if (otherCondition()) {`

There is no opening brace `{` after the `else`! 

I think the example is wrong, it doesn't follow the rule stated in the previous section.

**Comment by vapier** [comment]
I think you're misinterpreting the text.  `else if` is not banned, and braces are used with the `if` statement there.

**Comment by taurus227** [comment]
@vapier In Java there is no such thing as `elseif`, those are two separate `if` statements, so the second one should be surrounded by braces.

**Comment by eamonnmcmanus** [comment]
I think it is the rule rather than the example that could be addressed. The intent is certainly not to require people to write

```java
if (foo) {
  bar();
} else {
  if (baz) {
    ...
  }
}
```

Also, while we are nitpicking, the rule says "Braces are used with `if`, `else`, `for`, `do` and `while` statements", but `else` is not a statement.

**Comment by vapier** [comment]
no one said `elseif` is a keyword.  you seem to have misread what i wrote.

seeing as how you're a Googler, you know the public issue tracker is not where you need to debate/convince because no one in charge of the Java style guide is here.  talk to the internal Java style guide maintainers, or send them a CL to the internal version and get them to approve it.

**Comment by taurus227** [comment]
> I think it is the rule rather than the example that could be addressed.

@eamonnmcmanus Agreed, should be added as an exception to the rule.

@vapier I would if I was a Googler.

**Comment by eamonnmcmanus** [comment]
I *am* one of the internal Java style guide maintainers, though I'm not convinced anything needs to be changed here.

**Comment by vapier** [comment]
@eamonnmcmanus that is why I closed the report: I don't think anything needs to be changed as no one reasonably should read it and conclude "else if" should be treated as "else { if ... }", and if it did need changing, it should be done internally, and driven by someone who believes it should be done.
