### ISSUE TITLE
GSS => CSS (HTML/CSS Style Guide)

### ISSUE THREAD

**Issue by Denisandrik** [google/styleguide#418]
https://google.github.io/styleguide/htmlcssguide.html#Background

"including GSS files." => "including CSS files."

**Comment by tonyruscoe** [comment]
This isn’t a typo. _GSS_ refers to the file extension used by _Closure Stylesheets_, sometimes referred to as _Google Stylesheets_, which are widely used at Google.

More details: https://github.com/google/closure-stylesheets#css-extensions
