### ISSUE TITLE
Use C++14 as default standard version for cpp projects

### ISSUE THREAD

**Issue by dsazonoff** [google/styleguide#429]
Maybe it's time to update [C++ version](https://google.github.io/styleguide/cppguide.html#C++_Version) to C++14?

**Comment by tituswinters** [comment]
Unfortunately, few of Google's projects are C++14 based at this point. We
believe that most of our internal projects will move to C++17 soon, and
some of our external projects (starting with Abseil, I believe) will likely
push up to C++14 as a minimum version.  Balancing between "allow most
modern features" without cutting off users that are stuck on a lagging
compiler is tricky.

**Comment by dsazonoff** [comment]
I'm asking because I will contribute to [google agones cpp SDK](https://github.com/GoogleCloudPlatform/agones/tree/master/sdks/cpp) and I would like to use some features from cpp14. But we agreed to follow google codestyle. Thanks for your responce, I think that we should agree it with project leader.

**Comment by tituswinters** [comment]
Definitely.  For an external project with no technical ties to any
particular language version, I'd strongly suggest starting with at least
C++14, if not C++17.

**Comment by vapier** [comment]
current guide now says to use C++20 by default
