### ISSUE TITLE
Inconsistent java formatting with Eclipse and IntelliJ

### ISSUE THREAD

**Issue by jacek-jablonski** [google/styleguide#430]
Google Java style guide says nothing about blank lines after class declaration. 
However IntelliJ rules leaves blank line after class declaration:
[IntelliJ Rules](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml#L115)
whereas Eclipse rules define 0 blank lines:
[Eclipse Rules](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml#L97)

Which option is valid?

**Comment by jacek-jablonski** [comment]
And also IntelliJ config should define: BLANK_LINES_AFTER_IMPORTS to 1 as it is in [Eclipse](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml#L326)

**Comment by max-susi** [comment]
The inconsistency applies for other values too, for example the indentation size:
[eclipse indent size](https://github.com/google/styleguide/blob/5beae3f4dacad9b0b86a8a4ab308459475feda0e/eclipse-java-google-style.xml#L99) = 4
vs.
[intellij indent size](https://github.com/google/styleguide/blob/5beae3f4dacad9b0b86a8a4ab308459475feda0e/intellij-java-google-style.xml#L5) = 2

**Comment by apaatsio** [comment]
@max-susi That's a different issue and it's actually a *non-issue* as explained in the comments in https://github.com/google/styleguide/issues/98
