### ISSUE TITLE
Add Kotlin style guide

### ISSUE THREAD

**Issue by michl-b** [google/styleguide#470]
I would love to see your code style for Kotlin as a configuration file for IntelliJ

**Comment by vasudevravula** [comment]
https://developer.android.com/kotlin/style-guide

**Comment by criswonder** [comment]
refresh it

**Comment by tqkhanh29** [comment]
It's rated more than 1 year but why not for Kotlin?

**Comment by jolly336** [comment]
How it goes on?

**Comment by underwindfall** [comment]
up it. any update ?

**Comment by lowasser** [comment]
Google primarily uses the already-available [Android Kotlin style guide](https://developer.android.com/kotlin/style-guide), with only a handful of changes -- mostly that we use a 2-space indent.

For formatting, we primarily use [ktfmt](https://github.com/facebookincubator/ktfmt), which has an IntelliJ plugin.

**Comment by vapier** [comment]
thanks, fixed in commit 54fe3035bedc2a19896311c9ef804983e40530e0 now
