### ISSUE TITLE
Python - multi-Args / Returns indentation formatting

### ISSUE THREAD

**Issue by ColinKennedy** [google/styleguide#505]
The style guide for Python shows that arguments go on the first line and each line after are indented. This has led to some rather strange readability issues.

Such as this:

```python
        """Keep track of the current Rez package and the user's settings.

        Args:
            package: The current Rez package that is being checked.
            processed_packages: Other install Rez packages that have
                already been processed. These packages should be
                pre-validated and are meant only for caching. Default is None.
            allow_vimgrep: Some user input to track that specifies if they want row/column data printed.
            verbose: Some user input to track that specifies
                if they want summary information or everything to be
                printed.

        """
```

And this (pre-type annotations)

```python
def foo(something=[(8, 1.0), (-1, 11.0), (3, 4, 6, 7)], another_argument=frozenset(), more=None):
    """Do something.

    Args:
        something (iter[tuple[int, float] or tuple[int]], optional): My information.
        another_argument (set[str], optional): Lorem ipsum dolor sit amet, consectetur 
            adipiscing elit. Ut erat urna, finibus non tincidunt scelerisque, commodo eget ante. 
        more (None, optional): Aliquam vel justo convallis est sollicitudin egestas et quis arcu. 
           Nam ut mauris luctus, elementum dolor eu, placerat turpis. Ut non consequat augue, 
           sit amet dapibus arcu. Vivamus mattis dui vel mi condimentum, pellente
    """
```

Is it a requirement that the description start on the same line or may it start on the line below? (example)

```python
        """Keep track of the current Rez package and the user's settings.

        Args:
            package:
                The current Rez package that is being checked.
            processed_packages:
                Other install Rez packages that have already been
                processed. These packages should be pre-validated and
                are meant only for caching. Default is None.
            allow_vimgrep:
                Some user input to track that specifies if they want
                row/column data printed.
            verbose:
                Some user input to track that specifies if they want
                summary information or everything to be printed.

        """
```

What are the common strategies used when dealing with docstrings that mix single and multi-line descriptions in the same function?

**Comment by gpshead** [comment]
We've got a custom pylint GoogleDocstringChecker internally that verifies the our style of docstring format.  My internal response to this kind of question is generally to defer to whatever our lint checker implementation asks for when it comes to details like this.  Running your final example through that, it likes it.  Which is a strong indicator that we allow that nice readable form. :)

There is really no good reason for us to keep that pylint checker internal!  We just hadn't considered pushing that one upstream before.  We're slowly working to send more of our custom checkers to the upstream pylint project; this one would make a lot of sense as an optional checker given how many people use the Google style guide.   I've noted that in our internal tracking bug.

For your middle "pre-type annotations" one, don't put those before the colon.   From http://google.github.io/styleguide/pyguide.html#383-functions-and-methods
_"The description should include required type(s) if the code does not contain a corresponding type annotation."_   Overall, we're adopting PEP-484 type annotations as our common style for that.  The docstring description should mention types in a human friendly way, the annotation is the pedantic not always human friendly way to list types.

**Comment by ColinKennedy** [comment]
Thanks for the clarification. I've got one more question, if you don't mind.

> For your middle "pre-type annotations" one, don't put those before the colon

I was under the impression that the type was meant to be in parentheses since that's what napoleon teaches users to do.

[Example from their docs](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google)

```
    Args:
        msg (str): Human readable string describing the exception.
        code (:obj:`int`, optional): Error code.
```

Does that mean those examples are all technically wrong? I guess the other alternative is to use PEP-484 style types, as you mentioned.

**Comment by gpshead** [comment]
I'm not _aware_ of anyone at Google having worked on Sphinx's Napoleon.  It appears to have been added to sphinx in 2014 from an external project.  So I'd just call it a bit out of sync with our style and say "yes, it is wrong".
