### ISSUE TITLE
C++: Broken link in cppguide

### ISSUE THREAD

**Issue by mhbackes** [google/styleguide#507]
There is a broken link in subsection `Other C++ Features` -> `Rvalue References`:

"See the [C++ Primer](https://google.github.io/styleguide/primer#copying_moving) for more information about move semantics and std::move."

It refers to https://google.github.io/styleguide/primer#copying_moving, which I'm not sure what it is suposed to be.

**Comment by ArvindReddySheelam** [comment]
Hey, Hi! @mhbackes I am unable to find any broken links in the specified section you provided.

**Comment by vapier** [comment]
the broken link was fixed in commit 7a7a2f510efe7d7fc5ea8fbed549ddb31fac8f3e
