### ISSUE TITLE
Examples in "Builtin Commands vs. External Commands": Internal consistency improvements (Shell Style Guide rev. 2.02)

### ISSUE THREAD

**Issue by balanco** [google/styleguide#550]
Re: Shell Style Guide rev. 2.02:

Two suggested improvements of consistency of the example code in section ["Builtin Commands vs. External Commands"](https://google.github.io/styleguide/shellguide.html#builtin-commands-vs-external-commands) with other sections of the guide:

1. In the  _` # Prefer this`_ box,<br/>the line: `addition=$(( ${X} + ${Y} ))`<br/>could "just" read: `addition=$(( X + Y ))`,<br/>to conform with the _recommendation_  in the section [Arithmetic](https://google.github.io/styleguide/shellguide.html#arithmetic) of the Shell Style Guide,<br/>since the recommendation arguably _does_ apply to this particular case.<br/>(Still, a _"see also"_ link to the recommendation could be added to point out the recommendation's caveats).

2. In the  _` # Instead of this`_ box,<br/>the line: `addition="$(expr ${X} + ${Y})"`<br/>_should_ read : `addition="$( expr "${X}" + "${Y}" )"`,<br/>to conform with the section [Quoting](https://google.github.io/styleguide/shellguide.html#quoting) of the Shell Style Guide,<br/>since the added quotes help ensure that the intended _addition_  is attempted on the arguments, rather than any other operation that might be contained in string values of these variables.

Minor note:<br/>The heading 'Example:' should also be changed to the plural (i.e., 'Examples:'), since multiple (two) cases are stated.

**Comment by dimo414** [comment]
Thanks for the report, I'll try to address this.

**Comment by dimo414** [comment]
Addressed in 35fd3f0167, thanks again.
