### ISSUE TITLE
Secure GitHub Pages Site With HTTPS

### ISSUE THREAD

**Issue by ghost** [google/styleguide#564]
Currently, the GitHub Pages site for this repository is served over both HTTP and HTTPS, with no redirects from the insecure HTTP site to the secure HTTPS site:

- [http://google.github.io/styleguide/pyguide.html](http://google.github.io/styleguide/pyguide.html)
- [https://google.github.io/styleguide/pyguide.html](https://google.github.io/styleguide/pyguide.html)

The security benefits of HTTPS-by-default are clear. Google itself gives a [ranking boost to HTTPS sites](https://support.google.com/webmasters/answer/6033049?hl=en), and [Chrome displays a "Not Secure" indicator for HTTP sites](https://www.theverge.com/2018/7/24/17603126/google-chrome-unencrypted-not-secure).

This can be fixed by checking the "Enforce HTTPS" box in the repository settings, under the "GitHub Pages" section:

[https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

Thank you.

**Comment by tonyruscoe** [comment]
Done, thanks!
