### ISSUE TITLE
Table Of Contents in the pyguide.md does not render properly on github.io

### ISSUE THREAD

**Issue by gpshead** [google/styleguide#566]
It renders properly in Github's source tree view of pyguide.md, but on their different markdown implementation behind github.io it falls over and is a giant mess of text.

Fortunately it is collapsed by default so it doesn't look ugly without a click.

Thanks Github for the continual time wasting problem of deploying multiple incompatible markdown renderers.

**Comment by crazyczy** [comment]
@gpshead Hi, I tried to solve it, please take a look at the PR.

**Comment by gpshead** [comment]
thanks for the fix!
