### ISSUE TITLE
Shell - Command Chaining in place of if statement.

### ISSUE THREAD

**Issue by chuckwolber** [google/styleguide#567]
The [shell style guide](https://google.github.io/styleguide/shellguide.html) is relatively silent on the topic of using command chaining in place of an  ```if``` statement. I would propose the following guidance be considered.

In simple test and execute situations like the following:
```
if [[ -z "${VARIABLE} ]]; then
  exit 1
fi
```

Simplify the code into a more compact form for readability.
```
[[ -z "${VARIABLE}" ]] && exit 1
```

**Comment by eatnumber1** [comment]
One can easily argue that the compact form decreases readability because it's using almost exclusively shell special characters, and therefore is completely devoid of english language to ground the reader in what is being done.

Readability-wise, I find one vs. the other as most readable based upon what's being tested, and what the "then" clause is. If the test itself, or the "then" clause is complicated, then it's likely better to break it up for the reader into multiple lines.

This is similar to the C++ style guide's [advice](https://google.github.io/styleguide/cppguide.html#Conditionals) that omitting the brackets on `if` statements is allowed for short, single-line conditionals.

**Comment by eatnumber1** [comment]
That's not to mention that promoting use of `test && then` may then be extended by someone unfamiliar with shell into thinking that they can do `test && then || else`, which does not work in the expected way.

The style guide tries to guide folks away from shell pitfalls, and so in fact I'd see that as a potential argument that we should recommend against `test && then` entirely.

**Comment by chuckwolber** [comment]
> The style guide tries to guide folks away from shell pitfalls, and so in fact I'd see that as a potential argument that we should recommend against `test && then` entirely.

That is fine. I think it should be addressed either way. But I am a little wary of, "do not use this ever because this one bad thing could happen", so I agree that a nuanced discussion on the matter has some value.

**Comment by eatnumber1** [comment]
In general, I'm not sure we should spend a lot of time in the document talking about things we're explicitly choosing not to take a stance on. I think the only thing we're in real agreement on is that folks shouldn't use `test && then || else`, so spending time talking about `if test; then` vs. `test && then` when we don't actually make a recommendation of one vs. the other will likely be of limited value.

**Comment by chuckwolber** [comment]
Agreed. Shall I submit a pull request for the bits we agree on?

**Comment by eatnumber1** [comment]
Happy to review language that you're proposing, but what I'm saying is that I'm unsure that there'll be a lot of value in discussing it at all in the style guide, given that we're not actually making a recommendation.

That said, if you want to propose some specific language, happy to continue the discussion with that in hand.

**Comment by chuckwolber** [comment]
Ok, I thought on it for a while, and I see your point. There is too much nuance in the topic to make it useful in a succinct manner.

Unless there is anything more to discuss, I thank you for looking this over, and I am happy to close it.

**Comment by IsaacG** [comment]
Even if it were less nuanced, I don't think the guide is there to lay out a comprehensive opinion on every possible structure and language feature. The guide is a *style* guide. It's there to lay out a set of style rules that, when adopted, enforces a uniform style on a codebase. Enforcing a specific style does not mean having guidance on every feature. It's more about addressing the areas where styles often diverge and lead to a codebase that does not look uniform anymore. A codebase that always quotes using the same style and always tests using `[[` over `[` is a lot more pleasant to work with than one that does not. Having the occasional `if cond; then cmd; fi` mixed in with `cond && cmd` doesn't feel like the sort of thing that would make a codebase feel non-uniform. 

The style guide isn't there to have an opinion on every single scripting decision. It's there to enforce a codebase that looks consistent.

**Comment by chuckwolber** [comment]
Of course, and I wholeheartedly agree. Style is necessarily open ended and ceases to be "style" when defined too rigidly.

The purpose behind submitting the original issue stemmed from an internal discussion on the topic, which seemed to elevate it past triviality and individual preference to the "worth considering" category due to the some of the points made about its affect on uniformity and readability. 

@eatnumber1 was impressively spot on when he identified a significant part of the internal conversation:

> This is similar to the C++ style guide's [advice](https://google.github.io/styleguide/cppguide.html#Conditionals) that omitting the brackets on if statements is allowed for short, single-line conditionals.

With some on our team making statements like, "Well if Google recommends it for C++, why not Bash?", the obvious statement spills out - "I dunno, maybe we should ask.".

I hasten to add that the details of BASH were not lost on the team - BASH is not C++ and the propensity for abuse in the proposed BASH idiom was a core part of the counter-argument.

Once again @eatnumber1 got into everyone's heads and articulated the other side quite well:

> That's not to mention that promoting use of ```test && then``` may then be extended by someone unfamiliar with shell into thinking that they can do ```test && then || else```, which does not work in the expected way.

The request was fairly narrow for that very reason. But as is now clear, the fact that the request *HAD* to be that narrow is precisely *WHY* it is not a good candidate for the Style Guide.

It invites too much nuance and cannot be succinctly defined in a manner that can be universally applied to the concept of style.

**Comment by eatnumber1** [comment]
Thanks Chuck for the good discussion.
