### ISSUE TITLE
3.16.2 not found in pyguide.md

### ISSUE THREAD

**Issue by Sotaneum** [google/styleguide#571]
URL : https://github.com/google/styleguide/blob/gh-pages/pyguide.md

![image](https://user-images.githubusercontent.com/9214362/89541086-dc0f9b80-d838-11ea-96bd-c52b4320a41e.png)

I am not good at English. But I have a question. 3.16.2 not found in pyguide.md.

![image](https://user-images.githubusercontent.com/9214362/89541497-6bb54a00-d839-11ea-8954-0e8d0d738065.png)

But it's in the table of contents. Is that the way you intended it?

**Comment by gpshead** [comment]
whoops, that was unintentional.  thanks for the report!  some comments we use to manage bits to strip out or replace with different text internally vs externally had a typo which wound up editing the first half of 3.16.2 out.  fix coming shortly...

**Comment by gpshead** [comment]
fixed by https://github.com/google/styleguide/commit/7645d6365201e2a1d35be8de7bef0d84a6585c2d
