### ISSUE TITLE
`build system` link does not work in pyguide.md

### ISSUE THREAD

**Issue by Sotaneum** [google/styleguide#572]
URL : https://github.com/google/styleguide/blob/gh-pages/pyguide.md#31914-circular-dependencies

![image](https://user-images.githubusercontent.com/9214362/89702386-d4a4db00-d97b-11ea-9677-735980f56efd.png)

`build system` link does not work. 

What does `#typing-build-deps` mean?

**Comment by gpshead** [comment]
that was an errant link (to an internal only section).  one of our updates since fixed that.  thanks for pointing it out.
