### ISSUE TITLE
Why no Go code style?

### ISSUE THREAD

**Issue by xorcare** [google/styleguide#573]
Hello, are you planning to add Golang style guide?

**Comment by IsaacG** [comment]
There's no a whole lot on top of the Go language requirements that can be added. Golang already dictates pretty much everything. `go fmt` even does the formatting.

**Comment by vapier** [comment]
maybe we should add a link/sentence for go that just says "use `go fmt`" ?

**Comment by xorcare** [comment]
> There's no a whole lot on top of the Go language requirements that can be added. Golang already dictates pretty much everything. `go fmt` even does the formatting.

Maybe, but why then such things appear?
https://github.com/uber-go/guide

Or for example:

https://golang.org/doc/effective_go.html
https://github.com/golang/go/wiki/CodeReviewComments

It seems to me that not everything is as simple as it seems ...

**Comment by IsaacG** [comment]
1. Much of that content isn't style related. A style guide is not the same as a guide on effective coding or common patterns.
2. The internet is a vast place. The fact that something exists on it somewhere doesn't have much meaning.

**Comment by kscooo** [comment]
https://google.github.io/styleguide/go/index
