### ISSUE TITLE
Clarification on class attributes

### ISSUE THREAD

**Issue by tsoutsman** [google/styleguide#575]
```
class Aaa:
    BBB =  1
    def  __init__(self):
        self.ccc = 1
```
The [class section](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#384-classes) doesn't specify how to differentiate class attributes (i.e. `BBB`) and instance attributes (i.e. `ccc`). Is there a correct style?

**Comment by gpshead** [comment]
We don't have a standard way to differentiate between class and instance attributes in our standard.  As from the point of view of most classes and most users, they're always dealing with instances so it just doesn't matter where it was originally assigned.  Anything needing to be specifically called out as being a class attribute for some purpose or other (ex: something subclasses may wish to override) should just do so in whatever way seems appropriate in the text.

**Comment by Tecktron** [comment]
So basically you standard is just kinda shitty and you're too lazy to change it. Got it.
