### ISSUE TITLE
Markdown: the name of the language should be separated from the fence

### ISSUE THREAD

**Issue by john-cj** [google/styleguide#576]
There is a recommendation to use a space between `#` and the actual heading, but there is no space after the "fence".

* https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#add-spacing-to-headings
* https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#code

Currently:

````
## Heading

```c++
some code
```
````

Would be better:

````
## Heading

``` c++
some code
```
````

**Comment by dimo414** [comment]
All of the examples in that style guide do *not* have a space between the backticks and the language name. Although the [spec](https://github.github.com/gfm/#info-string) permits leading whitespace I don't think it's the norm.
