### ISSUE TITLE
Provide translation?

### ISSUE THREAD

**Issue by LiuJiLan** [google/styleguide#578]
I want to provide translation for Chinese users. Can this request be permitted? If so, how can I help?

**Comment by gpshead** [comment]
It'd be best to maintain translations within your own fork of the repo.

Given our levels of only occasional maintenance by people for each of our various programming language style guides, I don't expect we'd actually accept translation merges back into this repository. We are unlikely to have enough people on our end willing and able to review the translated text.

Regardless, I've pointed your offer out internally on some mailing lists in case anyone is interested in volunteering to help expand the accessibility of our guides to other languages.  No promises.

**Comment by abolfazlchaman** [comment]
Hi @gpshead, hope you are well. 
has the state of the maintenance of this repository changed since you made this comment back in 2020?

I want to translate the amazing JavaScript & the HTML/CSS Style Guides to Persian(Farsi) and would love to get an update/guidance.

**Comment by gpshead** [comment]
Same story. It's best to maintain such things in a fork.
