### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by xiedeacc** [google/styleguide#604]
as title, python2 will not be supported by end of 2020

bazel test //... if use python3, when cpplint test failed, nothing meaningful in test.log file. if use python2.7, test.log will tell you how to fix failure

**Comment by gpshead** [comment]
This bug report isn't being specific enough about what you find that isn't python3 and where.  _(regarding cpplint.py, there are other issues open about that and a forked cpplint repo exists that does support py3)_

**Comment by xiedeacc** [comment]
> This bug report isn't being specific enough about what you find that isn't python3 and where. _(regarding cpplint.py, there are other issues open about that and a forked cpplint repo exists that does support py3)_

which fork? https://github.com/cpplint/cpplint?

**Comment by xiedeacc** [comment]
> This bug report isn't being specific enough about what you find that isn't python3 and where. _(regarding cpplint.py, there are other issues open about that and a forked cpplint repo exists that does support py3)_

you're right, I found maybe bazel version lead this problem, if I user 0.17.2 and python2.7, everything goes well, python3 no hint info. but bazel 3.7.1 no hint  info whether python2.7 or python3

**Comment by xiedeacc** [comment]
> This bug report isn't being specific enough about what you find that isn't python3 and where. _(regarding cpplint.py, there are other issues open about that and a forked cpplint repo exists that does support py3)_

I close this issue then open a new one

**Comment by gpshead** [comment]
yes https://github.com/cpplint/cpplint seems to be the maintained cpplint.
