### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by lmeinecke** [google/styleguide#644]
Is there a resource that speaks to privacy concerns an organization may have about running these scripts against closed or distribution controlled source code? I did not see anything negative or positive but the concern was raised by our organization and we were hoping someone may have already done some analysis on this topic. This seems like a great resource we'd like to use but we need some assurance our source code isn't ending up in a Google cloud somewhere. 

Thanks in advance.

**Comment by gpshead** [comment]
It's open source. Anyone who has such concerns can audit the code themselves until they are satisfied.
