### ISSUE TITLE
How to stop complier is cpplint has error?

### ISSUE THREAD

**Issue by nickhuangxinyu** [google/styleguide#665]
I want to generate binary file only when no cpplint error existed.

I think the default behavior is just to check once, even cpplint found error, it can make out.

And next make, those error wont show again.

Can I make cpplint check a hard check, stop generate binary file and print out message everytime?

**Comment by vapier** [comment]
this sounds like a question about the build system you're using which is out of scope for this project.  try SO or similar site instead.
