### ISSUE TITLE
What is the "character line limit"?

### ISSUE THREAD

**Issue by scheib** [google/styleguide#67]
Documentation style guide states, ["Obey the character line limit wherever possible"](https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#character-line-limit), but where does the line limit come from? Is there a suggested one? Perhaps this is project specific and the text could read "Obey procjects' character line limit"?

**Comment by scheib** [comment]
@nodirt

**Comment by nodirt** [comment]
Yes, this is project-specific. I will make the change.

**Comment by nodirt** [comment]
PTAL 294c4479745da4f62d791fd33947749c451743e2
