### ISSUE TITLE
[shell] `git send-email --to "${reviewers}" ${ccs:+"--cc" "${ccs}"}` may typo

### ISSUE THREAD

**Issue by YoheiKonno** [google/styleguide#670]
An example in "Quoting",
```bash
git send-email --to "${reviewers}" ${ccs:+"--cc" "${ccs}"}
```
may typo.

```bash
git send-email --to "${reviewers}" ${ccs:+"--cc"} "${ccs}"
```
may be correct.

**Comment by shubhayu09** [comment]
Hey @YoheiKonno,
As this environment is new to me, so will you please help me out with this issue? 
It can be possible for a user to get confused while running this command. So, what should be done to avoid this typo?

**Comment by YoheiKonno** [comment]
Sorry, it was my misunderstanding.

```bash
git send-email --to "${reviewers}" ${ccs:+"--cc" "${ccs}"}
```
is correct.

this will be expanded to `git send-email --to "revierwer1 revierwer2" "--cc" "ccs1 ccs2"` when ccs is set.
when css is unset, this will be `git send-email --to "revierwer1 revierwer2"`.

on the other hand,
```bash
git send-email --to "${reviewers}" ${ccs:+"--cc"} "${ccs}"
```
this will be `git send-email --to "revierwer1 revierwer2" ""` when css is unset. it is not expected behavior, i think.
