### ISSUE TITLE
Python style guide: docstring for function args

### ISSUE THREAD

**Issue by jaroli** [google/styleguide#679]
Is it according to the style guide to put argument type in brackets?

```python
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Args:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    Returns:
        bool: Description of return value

    """
    return True
```
Example taken from: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by tkohli** [comment]
Do read https://google.github.io/styleguide/pyguide.html
Kindly close the issue.
