### ISSUE TITLE
### Describe the bug

### ISSUE THREAD

**Issue by DNAOFFICIALL** [google/styleguide#694]
### Describe the bug

**Problem**: after trying to connect to Local Host (without a server running) if I then go to Chainlist and try to add any network I will see that my current network is Localhost even though I am on Rinkeby.

https://user-images.githubusercontent.com/54408225/167589129-5a4df0bb-efc1-425f-8dda-ee26d6ef83e4.mp4

### Steps to reproduce

**Reproduction steps:**
1. Try to connect to Localhost - wait until says it's not possible
2. Click the top right cross button
3. Open a new window and go to [Chainlist](https://chainlist.org/)
4. Try to add a new network: here you'll see you are changing from Localhost to this new network, but in reality you are not in Localhost but in Rinkeby 

### Version

10.14.0

### Browser

Firefox

### Operating system

Linux

__Originally posted by @seaona in https://github.com/MetaMask/metamask-extension/issues/14671__

__Originally posted by @DNAOFFICIALL in https://github.com/DNAOFFICIALL/potential-eureka/issues/2__

__Originally posted by @DNAOFFICIALL in https://github.com/trustwallet/trust-web3-provider/issues/276__

**Comment by Myself1Ketra** [comment]
@DNAOFFICIALL

**Comment by gpshead** [comment]
reported the issue and user as spam
