### ISSUE TITLE
Flutter styleguide? 

### ISSUE THREAD

**Issue by dev-akshat** [google/styleguide#700]
Style guide for flutter is not available in Google official style guide repository. 

This flutter style guide is vague. 
[https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo)

**Comment by vapier** [comment]
we don't really have a flutter style guide.  we follow:
* https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
* https://dart.dev/effective-dart

the latter is already linked from our styleguide index
