### ISSUE TITLE
Style guide by google? Is this a joke? From the same people who gave us browser tabs and 4 different sound settings for a single button?

### ISSUE THREAD

**Issue by MapperMalte** [google/styleguide#774]
Whose idea was it to have 4 different sound settings on the same button, but the button only changes one of them? 

Then why is there a button?

Something loud is playing, I turn off the sound via the button ... STILL playing. GREAT google. YOU CLEARLY have very good understanding of user experience ... NOT.

Who the fuck gave us browser tabs?

What is with your product managers? What are they smoking? They should quit that. 

Like ... do you not EVER ask users for feedback before you rollout fucked up changes like the tab bars (which now can't even be deactivated) or have some genius idea to "why would anyone have ONE sound setting if you can have FOUR instead?)

Imagine a user setting his audio volume settings on max., but his alarm-sound is still at "0" so his alarm will literally not go off... WTF.

I know I am abusing your github (again) and you will ban me from here (again) but since you have like exactly NO channel to acquire user feedback from, this is neccessary. Someone has to tell you.

At least you stopped introducing breaking changes to Flutter at a retarded pace and asked this time in the developer survey, how retarded it actually is that you keep breaking flutter. Love flutter.

Best regards,
Malte

**Comment by vapier** [comment]
thank you for your feedback
