### ISSUE TITLE
FYI: the diamond problem is solved!

### ISSUE THREAD

**Issue by joortcom** [google/styleguide#781]
@pwnall

I'm reading: https://github.com/google/styleguide/blob/gh-pages/cppguide.html
esp about the multiple inheritance part.

And I just want to let you know: the diamond problem is solved! please check here:

https://github.com/joortcom/DDIFI

**The diamond problem solved!** Using virtual property to decouple the data dependency of the subclass on the superclass, as a **clean** and **general** solution to multiple inheritance.

If the company are interested, I can goto Google and give a presentation talk about the design pattern.

Regards.

**Comment by tituswinters** [comment]
IIUC, that is a solution if your tool is used AND if everyone is doing that consistently from the beginning.

**Comment by joortcom** [comment]
Previously people are haunted by the diamond problem, because there was no clean solution. That's why people and most programming style guide suggested avoiding MI as much as possible.

But, now we have a **clean and general** solution (I just invented this design pattern early this year). Then people can start using it: "better late than never" :-)

BTW: it's just a design pattern, can be used in a number of mainstream programming languages, no additional "tool" is needed.
