### ISSUE TITLE
translating style guides into other languages

### ISSUE THREAD

**Issue by Seo-yul** [google/styleguide#784]
This style guide helps developers set up their initial environment.
Therefore, I think it has a great influence on beginner users.
So I think It need to respond to l10n.

Any plans for the l10n?

**Comment by vapier** [comment]
what styleguide are you referring to ?  what localization settings are you talking about ?

**Comment by Seo-yul** [comment]
> what styleguide are you referring to ? what localization settings are you talking about ?

Thank you for your response.
The localization I'm referring to is the translation of the guide documentation language. 
(For example, English -> Korean).

**Comment by vapier** [comment]
translations of the style guides would be nice, but we don't translate them internally, and I don't see Google paying anyone to do it.

**Comment by Seo-yul** [comment]
I would like to have the opportunity to contribute....
thank you for your infomation!
