### ISSUE TITLE
styleguide.css doesn't follow https://google.github.io/styleguide/htmlcssguide.html

### ISSUE THREAD

**Issue by saritpatnaik** [google/styleguide#796]
The [styleguide.css ](https://github.com/google/styleguide/blob/gh-pages/styleguide.css) doesn't follow the formatting and style rules for HTML and CSS.
Especially this
https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation
https://google.github.io/styleguide/htmlcssguide.html#Shorthand_Properties

**Comment by tonyruscoe** [comment]
Acknowledged. This is because the stylesheets were written many years ago, before the HTML/CSS Style Guide had even been written. I’ll make some quick updates to make them more compliant but don’t want to mess about with them too much.
