### ISSUE TITLE
java: Egyptian brackets link is broken

### ISSUE THREAD

**Issue by jucaacuna** [google/styleguide#798]
Hello. In the Java Style Guide there is a broken link at line 269. Bye.
[HERE](
https://github.com/google/styleguide/blob/4d9a47834bfbadeb00a3dcf3d9808ffe49e43aeb/javaguide.html#L269)

**Comment by vapier** [comment]
hmm, it was fixed in the internal guide in Jan 2024 to use:
https://blog.codinghorror.com/new-programming-jargon/#3

not sure why it hasn't been synced to the public guide.

**Comment by vapier** [comment]
I just did a sync and should be fixed in cbc2e018266428c6f696f702672f22bdf2f5adbc.  thanks for the reminder.
