### ISSUE TITLE
Removed incorrect statement at /trunk/javascriptguide.xml#Semicolons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/styleguide#8]
```
Removed "unless resultOfOperation() is NaN". By the Abstract Equality 
Comparison Algorithm (ECMA-262, section 11.9.3, 1.c.i), the assertion "NaN == 
resultOfOperation()" is *always* false, even if resultOfOperation is NaN.

Quick link to the relevant section of the ECMAScript 5.1 specification: 
http://es5.github.com/#x11.9.3
```

Original issue reported on code.google.com by `robwu...@gmail.com` on 27 Jul 2012 at 1:04

Attachments:
- [javascriptguide.xml.patch](https://storage.googleapis.com/google-code-attachments/google-styleguide/issue-8/comment-0/javascriptguide.xml.patch)

**Comment by vapier** [comment]
we've archived the [older guide](https://google.github.io/styleguide/javascriptguide.xml) as it's for ES5, and the [newer guide](https://google.github.io/styleguide/jsguide.html) doesn't have this problem
