### ISSUE TITLE
issue:The length of the tab is extra.

### ISSUE THREAD

**Issue by sahiladit** [google/styleguide#810]
Steps to get this issue:
1:Open chrome browser
2:Open first tab
The length of the first tab at the left bottom is extra and does not merge with the bottom part of the nav.

<img width="110" alt="Screenshot 2024-03-17 at 8 42 20 PM" src="https://github.com/google/styleguide/assets/159920447/a0bb5e65-1464-4331-8c73-d560dd83d664">

**Comment by sahiladit** [comment]
Why do you closed this issue?

**Comment by vapier** [comment]
this GH project has nothing to do with the Chrome browser.  if you want to report an issue about the Chrome browser, please report it to them.

**Comment by sahiladit** [comment]
Is this is an issue?
