### ISSUE TITLE
Link to Python style guide returns 404

### ISSUE THREAD

**Issue by iamWing** [google/styleguide#846]
The URL <https://digon.io/hyd/project/scheduler/t/master/pages/examples/timezones.html> now returns a 404 page as of the time of writing. Is that page being moved elsewhere?

![image](https://github.com/user-attachments/assets/6e7e2f6d-c6d9-401f-a55b-78b92bb3aca7)

**Comment by vapier** [comment]
sorry, but what are you reporting ?  that digon.io has a broken link ?  we don't manage that website -- please report problems to them.

i can't see links from our repo to timezones.html either.
