### ISSUE TITLE
homepage: use larger CC-by image in footer

### ISSUE THREAD

**Issue by trivedikavya** [google/styleguide#856]
If you will increase the size of the photo which is at the last in contributing section it will look better { in this  https://google.github.io/styleguide/  }
if you can edit the image so plz do it becoz common creative looks good if it is written in the image (i can edit it if you  dm me in my instagram account (it is in my profile) )

**Comment by JaphyFan** [comment]
你好，你的邮件已收到,我会尽快回复。祝你工作顺利，生活愉快！

**Comment by vapier** [comment]
the image in question comes from the CC project themselves.  we could probably embed a larger version, but I think the current size looks fine.  thanks for the suggestion.
