### ISSUE TITLE
Please fix the f**king bug in google docs!

### ISSUE THREAD

**Issue by 221V** [google/styleguide#858]
Please fix the f**king bug in google docs!

I can not to find any feedback form for google products -
where bugs and proposals can be send by users,
so I will describe my pain here

there are f**king bug in google docs --
when you are working with book in google docs format --
and your internet connection is not stable --
or you just disconnect and connect again --

document is often reloaded and returns back to 1st page..((
is this too hard for famous - best on the planet - google software engineers -
to save page number and cursor posion -
and to scroll document back to that page and position after document-page reload after internet connection resumes ?

maybe any front-end js codemonkey can do that -- full stackoverflow of ready solutions ..
why google is so invalid sometimes?

so much engineers, so much money, so cool offices and work schedules -- and so stupid UI/UX ..
so stupid bugs..

details:
lubuntu 22.04 lts,
mozilla firefox browser 124.0 64 bit
sometimes very unstable mobile internet -- Ukraine and russian-moskovian invasion-war.. f**k russian-moskovian nazies!!

please fix the bug with google docs!
thank you!

**Comment by vapier** [comment]
this project has nothing to do with Google Docs.  please try their normal support channels instead.
