### ISSUE TITLE
golang

### ISSUE THREAD

**Issue by sijad** [google/styleguide#90]
any plan to add go style?

**Comment by aleksandr-vin** [comment]
Why? `go fmt` is not enough?

**Comment by nodirt** [comment]
cc:@adg

**Comment by andybons** [comment]
There is no Go style guide.

Use `go fmt`, https://golang.org/cmd/vet/, and https://github.com/golang/lint. They’re great tools for what you probably want.

Beyond [Effective Go](https://golang.org/doc/effective_go.html), there is this document on common code review comments made: https://github.com/golang/go/wiki/CodeReviewComments
